spring:
  application:
    name: departamentos-service

  datasource:
    url: jdbc:mysql://localhost:3306/departamentos

# Username and password
    username: maza
    password: maza

# Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1


  data:
    mongodb:
#      authentication-database: admin
#      username: root
#      password: root
      database: departamentos
#      port: 27017
#      host: localhost   

server:
  port: 7777
  
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
app:
  empleadosServiceAlias: empleados-service