spring:
  application:
    name: departamentos-service

  datasource:
    url: jdbc:mysql://localhost:3306/departamentos

# Username and password
    username: maza
    password: maza

# Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1


  data:
    mongodb:
#      authentication-database: admin
#      username: root
#      password: root
      database: departamentos
#      port: 27017
#      host: localhost   

  kafka:
    consumer:
      group-id: empleadosEvents
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
#  port: 7777
  port: ${PORT:0}  
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
app:
  empleadosServiceAlias: empleados-service
  empleadosTopic: empleados-events